### PR TITLE
Gavin/189 make return search results api update search history

### LINKED ISSUE #189: Make Return Search Results API Update Search History
## Feature Description
When the /api/search endpoint is called, the user id and query string should be inserted into the user_searches table.

relates: #50 

## Problem You're Trying to Solve
Once user searches are stored in the user_searches table, /api/user/search-history should be callable from the frontend. The most recent few rows of the user_searches table can be returned in descending timestamp order from the backend.

### PR DESCRIPTION
**Pull request by GDeane**
# Description
This PR gets the search API endpoint to update the user_searches table whenever a search is made. It also refactors the search engine code to be more readable.

This should be merged after [emila's reindexing PR](https://github.com/UVicMartletplace/martletplace/pull/201) If you have not reviewed that PR, do so first.

This PR does not include authorization. It uses user_id = 5 as a placeholder (@MNThomson said he'd manage that when setting up jwt token stuff)

Closes #189 

## How to Test
1. Checkout this branch

2. In a terminal, navigate to the martletplace directory and run `docker-compose up --build`

3. Wait a minute for the data layer (particularly elasticsearch) to get ready for input

4. In a terminal, run `docker exec -it martletplace_search bash`

5. In the bash terminal, run `pytest src/test_server.py`

## How to test manually
1. Uncomment the search engine port for testing purposes (DO NOT COMMIT THIS CHANGE) 
image

2. Run a fresh `docker-compose up --build`
3. Once everything is up and running, run `docker-exec -it martletplace_database base`
4. In the bash terminal, run `psql -p 8310 -U martletplace -h localhost`
5. run `select * from user_searches;` 
image

6. In your browser, navigate to http://localhost:8221/docs
image

7. Open the search endpoint, click "try it out", fill in some (valid) dummy values, and click 'execute' 
image

8. In the database bash terminal, run `select * from user_searches;` 

9. The table should have an additional entry for user_id = 5

## Checklist
- [X] The code includes tests if relevant
- [X] I have *actually* self-reviewed my changes and done QA

### CODE REVIEW

**Comment by GDeane** [comment]
Currently the testing is finicky, trying to figure it out

**Comment by GDeane** [comment]
Now it's mostly working. I just need to write tests for this functionality

**Review by emilasuska — COMMENTED** [review]
LGTM

**Review by emilasuska — COMMENTED** [review]
LGTM

**Review by MNThomson — APPROVED** [review]
LGTM for oneline docker compose change

**Review by emilasuska — APPROVED** [review]

**Pull request merged**
